#!/usr/bin/env bash

# cd in the previous directory.
alias cdp="cd ~-"
alias ..='cd -- ..'
alias ...='cd -- ../..'
# Display all files and directories including the hidden ones, with precision.
# Make the terminal say all the files and directories.
alias lt="/bin/ls | say -va"
# exa love
# alias ls='exa'
# alias la='exa -la --sort modified'
alias l='exa -a --git-ignore'
alias ll='exa -la --git-ignore --git --sort modified'
# or not
alias ls='ls -AG'
alias -g la='ls -lArth'
# alias la='exa -la --sort modified'
# alias l='exa -a --git-ignore'
# alias ll='exa -la --git-ignore --sort modified'

# confirm && verbose
# alias	cp="cp -i"
alias	mv="mv -i"
# alias	rm="rm -v"
# Open the given directory in finder.
alias f='open .'
# Clear the terminal
alias c='clear'
# Beautiful Cat
# alias cat='colorize'
# Prevent the system from sleeping for one hour.
alias cafe='caffeinate -t 3600 &'
# Display a clock on the upper right hand side of the terminal.
alias clock='while sleep 1;do tput sc;tput cup 0 $(($(tput cols)-29));date;tput rc;done &'
# Open mac vim
alias mvim='open -a macvim'
# Open tmux
alias tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
# alias mux="tmuxinator"
# Using neovim
alias -g vim="nvim"
alias -g vimdiff="nvim -d"
alias ivm="nvim"
# load vim with very basic settings (way faster)
alias vi="vi -u ${XDG_CONFIG_HOME:-$HOME/.config}/vim/.vimrc"
# upgrade neovim nightly
alias upgrade-neovim-nightly='asdf uninstall neovim nightly && asdf install neovim nightly'
# dotfiles
alias cdd="cd $HOME/.dotfiles.git/master"
alias dot='/usr/bin/git --git-dir=$HOME/.dotfiles.git/worktrees/bare --work-tree=$HOME'

# weather
alias weather="curl wttr.in/montreal"
# suffix alias
alias -s md=nvim
#docker
# List all exited containers
alias dpsa="docker ps -aq -f status=exited"
# Remove stopped containers
alias drms="docker ps -aq --no-trunc | xargs docker rm"
# Remove dangling/untagged images
alias drmd="docker images -q --filter dangling=true | xargs docker rmi"
# bat > cat
alias cat="bat"
# kill
alias killseg="kill -s SIGSEGV $$"

alias tldrf='tldr --list | fzf --preview "tldr --color=always {1}" --preview-window=right,70% | xargs tldr'

# +-----+
# | Git |
# +-----+
alias g='git'
alias gco='git checkout'
alias gl='git pull'
alias gst='git status'
alias ga='git add'
alias gc='git commit -v -s'
alias gc!='git commit -v -s --amend'
alias gcn!='git commit -v -s --no-edit --amend'
alias gp='git push'
alias gbr='git branch --sort=-committerdate | fzf --header "Checkout Recent Branch" --preview "git diff --color=always {1}" --pointer="" | xargs git checkout'

# hub alias
eval "$(hub alias -s)"
alias gprm="git pull-request -a samuelmasuy"
alias ci="git ci-status"

alias gpr="gh prs"
alias gprc="gh pr checks -w"


# +-----+
# | k8s |
# +-----+
command -v kubecolor >/dev/null 2>&1 && alias kubectl="kubecolor"
alias -g k=kubectl
alias kn=kubens
alias kx=kubectx
# alias kx=kubeswap
alias minikube='DOCKER_DEFAULT_PLATFORM=linux/arm64/v8 minikube'
