#!/usr/bin/env zsh
set -e

dry_run=false
while getopts 'd' opt; do
    case "$opt" in
        d) dry_run=true ;;
        *) echo 'error in command line parsing' >&2
           exit 1
    esac
done

pushd $DOTFILES_HOME
source ./zsh/dot-zshenv
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
  if "$dry_run"; then
    stow --simulate --dotfiles -vv -D $folder
    stow --simulate --dotfiles -vv $folder
  else
    stow --dotfiles -D $folder
    stow --dotfiles $folder
  fi
done
popd
