[style.command_name]
foreground = "cyan"
bold = true

[style.example_text]
foreground = "green"
italic = true

[style.example_code]
foreground = "cyan"

[style.example_variable]
foreground = "cyan"
underline = true

[display]
compact = true
use_pager = true

[updates]
auto_update = true
auto_update_interval_hours = 360
