#!/usr/bin/env bash

set -euo pipefail

__list_installed_plugins() {
    asdf plugin-list 2>/dev/null | sort
}

__list_installed_versions() {
    asdf list $1 2>/dev/null
}

__select_installed_version() {
    __list_installed_versions $1 | \
    fzf --tac --ansi --no-sort | \
    awk '{print $1}'
}

main() {
    plugin=`__list_installed_plugins | fzf`
    __select_installed_version $plugin | xargs -t -r -n 1 asdf global $plugin
}

main
