#!/usr/bin/env bash

# cd in the previous directory.
alias cdp="cd ~-"
alias ..='cd -- ..'
alias ...='cd -- ../..'
alias ....='cd -- ../../..'
# Use z to jump around
alias cd='z'
# z with fzf
alias zz='zi'

# eza for ls
alias l='eza -a --git-ignore'
alias lf='eza -lF --color=always | grep -v /'
alias lh='eza -dl .* --group-directories-first'
alias ll='eza -la --no-permissions --no-user --git-ignore --git --sort modified --icons always'
alias la='eza -la --git --sort modified --icons always'
alias ls='eza -AG'
# Make the terminal say all the files and directories.
alias lt="/bin/ls | say -va"

# confirm && verbose
# alias	cp="cp -i"
alias mv="mv -i"
# alias	rm="rm -v"
# Open the given directory in finder.
alias f='open .'
# Clear the terminal
alias c='clear'
# bat > cat
alias cat="bat"
# Prevent the system from sleeping for one hour.
alias cafe='caffeinate -t 3600 &'
# Open tmux
alias tmux='tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf'
# Using neovim
alias -g vim="TERM=tmux-direct nvim"
alias -g vimdiff="TERM=tmux-direct nvim -d"
alias ivm="TERM=tmux-direct nvim"
# load vim with very basic settings
alias vi='vi -u ${XDG_CONFIG_HOME:-$HOME/.config}/vim/.vimrc'
# upgrade neovim nightly
alias upgrade-neovim-nightly='mise uninstall neovim:neovim@nightly && mise install neovim:neovim@nightly'
# dotfiles
alias cdd='cd $DOTFILES_HOME'

# weather
alias weather="curl wttr.in/montreal"
# suffix alias
alias -s md=nvim
# kill
alias killseg="kill -s SIGSEGV $$"

# tldr with fzf
alias tldrf='tldr --list | fzf --preview "tldr --color=always {1}" --preview-window=right,70% | xargs tldr'

# +-----+
# | Git |
# +-----+
alias g='git'
alias gl='git pull'
alias gst='git status'
alias ga='git add'
alias gc='git commit -v -s'
alias gc!='git commit -v -s --amend'
alias gcn!='git commit -v -s --no-edit --amend'
alias gp='git push'
alias gbr='git branch --sort=-committerdate | fzf --header "Checkout Recent Branch" --preview "git diff --color=always {1}" --pointer="" | xargs git checkout'

alias ci="gh pr checks"

alias gpr="gh prs"
alias gprc="gh pr checks -w"

# +-----+
# | k8s |
# +-----+
command -v kubecolor >/dev/null 2>&1 && alias kubectl="kubecolor"
alias -g k=kubectl
alias ks='kubectl -n kube-system'
alias kn=kubens
alias kx=kubectx
# alias kx=kubeswap
alias minikube='DOCKER_DEFAULT_PLATFORM=linux/arm64/v8 minikube'

alias oc=opencode
